import { vec } from "@/domain/coords";
import type { Shape, ShapeKind } from "@/domain/geometry";

import type { Chapter, Mission, SceneConfig, Tools } from "./types";

export const COLORS = {
  red: "#e5534b",
  orange: "#f59f00",
  blue: "#4dabf7",
  green: "#51cf66",
  wood: "#c8915f",
  stone: "#adb5bd",
  yellow: "#fcc419",
  purple: "#9775fa",
} as const;

const tools = (over: Partial<Tools> = {}): Tools => ({
  viewCube: false,
  orbit: false,
  shapes: [],
  rulerMove: false,
  rulerToggle: false,
  align: false,
  onObject: false,
  ...over,
});

const LINE: SceneConfig = { dims: 1, unit: "cell", min: -8, max: 8, zMax: 0, camera: "line", ruler: false };
const PLANE: SceneConfig = { dims: 2, unit: "cell", min: -8, max: 8, zMax: 0, camera: "top", ruler: false };
const SPACE: SceneConfig = { dims: 3, unit: "cell", min: -8, max: 8, zMax: 8, camera: "iso", ruler: false };
const MM: SceneConfig = {
  dims: 3,
  unit: "mm",
  min: -100,
  max: 100,
  zMax: 60,
  camera: "iso",
  ruler: true,
  frame: 70,
};

const SPACE_TOOLS = tools({ viewCube: true, orbit: true });
const MM_TOOLS = tools({ viewCube: true, orbit: true, onObject: true });

/** Neue Form aus den Grundformen: wie in Tinkercad 20 × 20 × 20 mm. */
export function newShape(kind: ShapeKind, id: string): Shape {
  return {
    id,
    kind,
    pos: vec(0, 0, 0),
    size: vec(20, 20, 20),
    color: kind === "cylinder" ? COLORS.orange : COLORS.red,
  };
}

export const CHAPTERS: Chapter[] = [
  { id: 1, title: "chapter.1.title", tinkercad: ["chapter.1.tc1", "chapter.1.tc2", "chapter.1.tc3"] },
  { id: 2, title: "chapter.2.title", tinkercad: ["chapter.2.tc1", "chapter.2.tc2", "chapter.2.tc3"] },
  { id: 3, title: "chapter.3.title", tinkercad: ["chapter.3.tc1", "chapter.3.tc2", "chapter.3.tc3"] },
  { id: 4, title: "chapter.4.title", tinkercad: ["chapter.4.tc1", "chapter.4.tc2", "chapter.4.tc3"] },
  { id: 5, title: "chapter.5.title", tinkercad: ["chapter.5.tc1", "chapter.5.tc2", "chapter.5.tc3"] },
];

export const MISSIONS: Mission[] = [
  // Kapitel 1 – Zahlengerade
  {
    id: "1.1",
    chapter: 1,
    type: "goto",
    title: "m1.1.title",
    goal: "m1.1.goal",
    intro: ["m1.1.intro1", "m1.1.intro2", "m1.1.intro3", "m1.1.intro4"],
    success: "m1.1.success",
    scene: { ...LINE, min: 0 },
    tools: tools(),
    targets: [vec(6)],
    item: "crystal",
  },
  {
    id: "1.2",
    chapter: 1,
    type: "goto",
    title: "m1.2.title",
    goal: "m1.2.goal",
    intro: ["m1.2.intro1", "m1.2.intro2", "m1.2.intro3"],
    success: "m1.2.success",
    scene: LINE,
    introFrom: { min: 0 },
    tools: tools(),
    targets: [vec(-4)],
    item: "crystal",
  },
  {
    id: "1.3",
    chapter: 1,
    type: "read",
    title: "m1.3.title",
    goal: "m1.3.goal",
    intro: ["m1.3.intro1", "m1.3.intro2"],
    success: "m1.3.success",
    scene: LINE,
    tools: tools(),
    items: [
      { pos: vec(5), kind: "crystal" },
      { pos: vec(-3), kind: "crystal" },
    ],
  },
  // Kapitel 2 – Ebene
  {
    id: "2.1",
    chapter: 2,
    type: "goto",
    title: "m2.1.title",
    goal: "m2.1.goal",
    intro: ["m2.1.intro1", "m2.1.intro2", "m2.1.intro3", "m2.1.intro4"],
    success: "m2.1.success",
    scene: PLANE,
    introFrom: LINE,
    tools: tools(),
    targets: [vec(3, 4)],
    item: "crystal",
  },
  {
    id: "2.2",
    chapter: 2,
    type: "read",
    title: "m2.2.title",
    goal: "m2.2.goal",
    intro: ["m2.2.intro1", "m2.2.intro2"],
    success: "m2.2.success",
    scene: PLANE,
    tools: tools(),
    items: [{ pos: vec(2, 5), kind: "treasure" }],
  },
  {
    id: "2.3",
    chapter: 2,
    type: "goto",
    title: "m2.3.title",
    goal: "m2.3.goal",
    intro: ["m2.3.intro1", "m2.3.intro2", "m2.3.intro3"],
    success: "m2.3.success",
    scene: PLANE,
    tools: tools(),
    targets: [vec(-4, 3), vec(2, -5), vec(-3, -2)],
    item: "crystal",
  },
  {
    id: "2.4",
    chapter: 2,
    type: "build",
    title: "m2.4.title",
    goal: "m2.4.goal",
    intro: ["m2.4.intro1", "m2.4.intro2", "m2.4.intro3"],
    success: "m2.4.success",
    scene: PLANE,
    tools: tools(),
    fixed: [],
    editable: [{ id: "plate", kind: "plate", pos: vec(0, 0, 0), size: vec(1, 1, 0), color: COLORS.green }],
    targets: [{ kind: "plate", pos: vec(-2, 1, 0), size: vec(5, 3, 0) }],
    ghost: "always",
    ghostStyle: "soil",
    fields: ["x", "y", "w", "d"],
    kubiSpot: vec(5, -5),
  },
  // Kapitel 3 – Raum
  {
    id: "3.1",
    chapter: 3,
    type: "goto",
    title: "m3.1.title",
    goal: "m3.1.goal",
    intro: ["m3.1.intro1", "m3.1.intro2", "m3.1.intro3"],
    success: "m3.1.success",
    scene: SPACE,
    introFrom: PLANE,
    tools: tools(),
    targets: [vec(2, 3, 4)],
    item: "star",
  },
  {
    id: "3.2",
    chapter: 3,
    type: "read",
    title: "m3.2.title",
    goal: "m3.2.goal",
    intro: ["m3.2.intro1", "m3.2.intro2", "m3.2.intro3"],
    success: "m3.2.success",
    scene: SPACE,
    tools: tools({ viewCube: true }),
    items: [{ pos: vec(-3, 2, 5), kind: "balloon" }],
  },
  {
    id: "3.3",
    chapter: 3,
    type: "goto",
    title: "m3.3.title",
    goal: "m3.3.goal",
    intro: ["m3.3.intro1", "m3.3.intro2"],
    success: "m3.3.success",
    scene: SPACE,
    tools: SPACE_TOOLS,
    targets: [vec(4, -2, 3), vec(-5, -4, 1), vec(0, 5, 6)],
    item: "star",
  },
  // Kapitel 4 – Körper & Größen (mm)
  {
    id: "4.1",
    chapter: 4,
    type: "build",
    title: "m4.1.title",
    goal: "m4.1.goal",
    intro: ["m4.1.intro1", "m4.1.intro2", "m4.1.intro3", "m4.1.intro4"],
    success: "m4.1.success",
    scene: { ...MM, frame: 45 },
    introFrom: { ...SPACE, ruler: false },
    tools: { ...MM_TOOLS, shapes: ["box"] },
    fixed: [],
    editable: [],
    targets: [{ kind: "box", pos: vec(0, 0, 0), size: vec(16, 16, 16) }],
    ghost: "always",
    ghostStyle: "dice",
    fields: ["x", "y", "z", "w", "d", "h"],
    kubiSpot: vec(-30, -20),
  },
  {
    id: "4.2",
    chapter: 4,
    type: "build",
    title: "m4.2.title",
    goal: "m4.2.goal",
    intro: ["m4.2.intro1", "m4.2.intro2", "m4.2.intro3"],
    success: "m4.2.success",
    scene: { ...MM, frame: 55 },
    tools: MM_TOOLS,
    fixed: [
      {
        id: "base",
        kind: "box",
        pos: vec(-20, -10, 0),
        size: vec(40, 20, 10),
        color: COLORS.wood,
        fixed: true,
      },
    ],
    editable: [{ id: "top", kind: "box", pos: vec(40, 20, 0), size: vec(20, 20, 10), color: COLORS.red }],
    targets: [{ kind: "box", pos: vec(-20, -10, 10), size: vec(20, 20, 10) }],
    ghost: "always",
    ghostStyle: "plain",
    fields: ["x", "y", "z", "w", "d", "h"],
    kubiSpot: vec(-50, -30),
  },
  {
    id: "4.3",
    chapter: 4,
    type: "build",
    title: "m4.3.title",
    goal: "m4.3.goal",
    intro: ["m4.3.intro1", "m4.3.intro2", "m4.3.intro3"],
    success: "m4.3.success",
    scene: { ...MM, frame: 60 },
    tools: { ...MM_TOOLS, rulerToggle: true },
    fixed: [
      {
        id: "plate",
        kind: "box",
        pos: vec(10, 10, 0),
        size: vec(40, 20, 10),
        color: COLORS.wood,
        fixed: true,
      },
    ],
    editable: [
      { id: "cyl", kind: "cylinder", pos: vec(-50, -40, 0), size: vec(10, 10, 20), color: COLORS.orange },
    ],
    targets: [{ kind: "cylinder", pos: vec(25, 15, 10), size: vec(10, 10, 20) }],
    ghost: "help",
    ghostStyle: "plain",
    markers: [vec(30, 20, 10)],
    fields: ["x", "y", "z", "w", "d", "h"],
    kubiSpot: vec(-75, 25),
  },
  // Kapitel 5 – Tinkercad-Werkzeuge
  {
    id: "5.1",
    chapter: 5,
    type: "build",
    title: "m5.1.title",
    goal: "m5.1.goal",
    intro: ["m5.1.intro1", "m5.1.intro2", "m5.1.intro3"],
    success: "m5.1.success",
    scene: { ...MM, frame: 65 },
    tools: { ...MM_TOOLS, rulerToggle: true, rulerMove: true },
    fixed: [
      {
        id: "table",
        kind: "box",
        pos: vec(-40, -30, 0),
        size: vec(60, 40, 30),
        color: COLORS.wood,
        fixed: true,
      },
    ],
    editable: [
      { id: "lamp", kind: "cylinder", pos: vec(50, 40, 0), size: vec(10, 10, 15), color: COLORS.yellow },
    ],
    targets: [{ kind: "cylinder", pos: vec(-30, -20, 30), size: vec(10, 10, 15) }],
    ghost: "help",
    ghostStyle: "plain",
    fields: ["x", "y", "z", "w", "d", "h"],
    expectedOrigin: vec(-40, -30, 0),
    rulerSpots: [vec(-40, -30, 0), vec(20, -30, 0), vec(-40, 10, 0), vec(20, 10, 0)],
    kubiSpot: vec(-70, -40),
  },
  {
    id: "5.2",
    chapter: 5,
    type: "build",
    title: "m5.2.title",
    goal: "m5.2.goal",
    intro: ["m5.2.intro1", "m5.2.intro2", "m5.2.intro3"],
    success: "m5.2.success",
    scene: { ...MM, frame: 60 },
    tools: { ...MM_TOOLS, rulerToggle: true, rulerMove: true, align: true },
    fixed: [
      {
        id: "wall",
        kind: "box",
        pos: vec(-30, -10, 0),
        size: vec(60, 20, 20),
        color: COLORS.stone,
        fixed: true,
      },
    ],
    editable: [
      { id: "tower", kind: "cylinder", pos: vec(30, -50, 0), size: vec(16, 16, 40), color: COLORS.blue },
    ],
    targets: [{ kind: "cylinder", pos: vec(-8, -8, 0), size: vec(16, 16, 40) }],
    ghost: "help",
    ghostStyle: "plain",
    fields: ["x", "y", "z", "w", "d", "h"],
    alignKeyId: "wall",
    rulerSpots: [vec(0, 0, 0), vec(-30, -10, 0)],
    kubiSpot: vec(-60, -40),
  },
  {
    id: "5.3",
    chapter: 5,
    type: "build",
    title: "m5.3.title",
    goal: "m5.3.goal",
    intro: ["m5.3.intro1", "m5.3.intro2", "m5.3.intro3"],
    success: "m5.3.success",
    scene: { ...MM, frame: 55 },
    tools: { ...MM_TOOLS, rulerToggle: true, rulerMove: true, shapes: ["box", "cylinder"] },
    fixed: [
      {
        id: "legL",
        kind: "box",
        pos: vec(-30, -10, 0),
        size: vec(5, 20, 20),
        color: COLORS.wood,
        fixed: true,
      },
    ],
    editable: [],
    targets: [
      { kind: "box", pos: vec(25, -10, 0), size: vec(5, 20, 20) },
      { kind: "box", pos: vec(-30, -10, 20), size: vec(60, 20, 5) },
    ],
    ghost: "help",
    ghostStyle: "plain",
    fields: ["x", "y", "z", "w", "d", "h"],
    rulerSpots: [vec(0, 0, 0), vec(-30, -10, 0)],
    blueprint: "bench",
    kubiSpot: vec(-60, -40),
  },
];

export const missionById = (id: string): Mission | undefined => MISSIONS.find((m) => m.id === id);
export const missionIndex = (id: string): number => MISSIONS.findIndex((m) => m.id === id);
export const chapterMissions = (chapter: number): Mission[] => MISSIONS.filter((m) => m.chapter === chapter);
